### PR TITLE
Generate legend icon for multiple symbolizers

### PR DESCRIPTION
**Pull request by raitisbe**
https://github.com/geostyler/geostyler-legend/issues/285
This generates legend icon when the parsed symbolizers return multiple OL styles or a style function in case of text symbolizer.

### CODE REVIEW

**Review by KaiVolland — COMMENTED** [review]
Thanks for your contribution. Looks nice.

Would be nice if you could add the `Ol` prefix for the imports to keep it in line with the other imports. You may also want to use `StyleLike` (`OlStyleLike`) instead of `OlStyle[] | OlStyle | StyleFunction`.

**Comment by raitisbe** [comment]
> StyleLike

Thanks will, do

**Review by KaiVolland — APPROVED** [review]
Seems like the coverage dropped below the threshold.

If your familiar with the tests I'd appreciate if you could add some tests for multiple symbolizers. If not I may add some next week.

**Comment by KaiVolland** [comment]
Awesome! Thank you.

**Pull request merged**
